# Generated by Django 5.0.1 on 2024-01-18 04:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0008_alter_fotografia_publicada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fotografia',
            new_name='Foto',
        ),
        migrations.RenameField(
            model_name='foto',
            old_name='data_fotografia',
            new_name='data_foto',
        ),
    ]
