# Generated by Django 5.0.1 on 2024-01-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0009_rename_fotografia_foto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foto',
            old_name='nome',
            new_name='titulo',
        ),
        migrations.AlterField(
            model_name='foto',
            name='categoria',
            field=models.CharField(choices=[('NULL', ''), ('NEBULOSA', 'Nebulosa'), ('ESTRELA', 'Estrela'), ('GALÁXIA', 'Galáxia'), ('PLANETA', 'Planeta')], default='', max_length=100),
        ),
    ]
