# Generated by Django 5.0.1 on 2024-01-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0010_rename_nome_foto_titulo_alter_foto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='categoria',
            field=models.CharField(choices=[('NULL', ''), ('ESTRELA', 'Estrela'), ('GALÁXIA', 'Galáxia'), ('NEBULOSA', 'Nebulosa'), ('PLANETA', 'Planeta')], max_length=100),
        ),
    ]
